default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: smartserver_development
  username:
  password:

test:
  <<: *default
  database: smartserver_test
  username:
  password:
